AWSTemplateFormatVersion: 2010-09-09
Description: Lambda functions to send telegram.
Parameters:
  TelegramToken:
    Description: Telegram API key
    Type: String
Resources:
  # SNS Topic to send telegram
  TelegramSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: telegram
      TopicName: Telegram-Topic
  
  TelegramSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref TelegramSNSTopic 
      PolicyDocument: 
        Id: TelegramSNSTopicPolicy 
        Version: 2012-10-17 
        Statement: 
          - Sid: SNS and Lambda
            Effect: Allow 
            Principal: 
              Service: 
              - lambda.amazonaws.com
            Action: 
              - sns:Publish 
            Resource: 
              - !GetAtt LambdaFunction.Arn       

  LambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref TelegramSNSTopic
      Endpoint: !GetAtt LambdaFunction.Arn
      Protocol: lambda   

  SNSLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref TelegramSNSTopic

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
      FunctionName: send-telegram
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.11
      Timeout: 500
      Code:
        ZipFile: | 
          import json
          import os
          import requests

          def lambda_handler(event, context):
              # TODO implement
              BOT_TOKEN = os.environ.get('TELEGRAM_TOKEN')
              data = event['Records']
              record = data[0]
              msg = record['Sns']['Message']
              chat_id = record['Sns']['MessageAttributes']['TelegramId']['Value']
              
              send_text = f'https://api.telegram.org/bot{BOT_TOKEN}/sendMessage?chat_id={chat_id}&parse_mode=HTML&text={msg}'
              response = requests.get(send_text)
              print(response)    
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
